name: "Tunet"
description: "A modern, responsive dashboard for Home Assistant"
version: "1.3.2"
slug: "tunet"
url: "https://github.com/oyvhov/Tunet"
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 3002
panel_icon: "mdi:view-dashboard-variant"
panel_title: "Tunet"
ports:
  3002/tcp: null
ports_description:
  3002/tcp: "Tunet Web Interface (not needed when using Ingress)"
options: {}
schema: {}
